# Generated by Django 2.2.8 on 2019-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='numder_of_pigbacks',
        ),
        migrations.AddField(
            model_name='entry',
            name='number_of_pigbacks',
            field=models.IntegerField(default=0),
        ),
    ]
