# Generated by Django 3.0 on 2019-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='운동 카테고리'),
        ),
    ]
