# Generated by Django 3.0 on 2019-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20191206_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='설명'),
            preserve_default=False,
        ),
    ]
