# Generated by Django 3.0 on 2019-12-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercises'),
            preserve_default=False,
        ),
    ]
