# Generated by Django 3.0 on 2019-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercise_exercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='exercise.Exercises'),
        ),
    ]
