# Generated by Django 3.0 on 2019-12-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20191206_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='운동 카테고리')),
                ('description', models.CharField(max_length=255, verbose_name='설명')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='calorie',
            field=models.IntegerField(blank=True, default=1, verbose_name='칼로리'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='descriptions',
            field=models.TextField(null=True, verbose_name='운동설명'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='english_name',
            field=models.CharField(default=1, max_length=255, verbose_name='영어이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='power',
            field=models.CharField(blank=True, max_length=255, verbose_name='운동강도'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(blank=True, default=1, verbose_name='시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='운동이름'),
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Category'),
            preserve_default=False,
        ),
    ]
