# Generated by Django 3.0 on 2019-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20191206_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='images',
            field=models.ImageField(blank=True, upload_to='exercise/action', verbose_name='운동 이미지'),
        ),
    ]
