# Generated by Django 2.2.8 on 2019-12-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_exercise_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': '운동들', 'verbose_name_plural': '운동들'},
        ),
    ]
