# Generated by Django 2.2.8 on 2019-12-12 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20191211_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='번호')),
                ('ex_description', models.TextField(verbose_name='운동설명')),
            ],
        ),
        migrations.DeleteModel(
            name='Descriptions',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='power',
            field=models.CharField(choices=[('W', '약함'), ('N', '중간'), ('S', '강함')], max_length=1, verbose_name='운동강도'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseDescriptions'),
        ),
    ]
