# Generated by Django 2.2.8 on 2019-12-12 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_auto_20191211_2344'),
        ('exercise', '0012_auto_20191212_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisedescriptions',
            options={'verbose_name': '운동설명', 'verbose_name_plural': '운동설명'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='images',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Category', verbose_name='운동카테고리'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseDescriptions', verbose_name='운동설명'),
        ),
        migrations.AlterField(
            model_name='exercisedescriptions',
            name='number',
            field=models.IntegerField(default=1, verbose_name='운동설명번호'),
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.IntegerField(verbose_name='운동이미지번호')),
                ('exe_image', models.ImageField(upload_to='exercise/action', verbose_name='운동이미지')),
                ('exe_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Trainer', verbose_name='트레이너')),
            ],
            options={
                'verbose_name': '운동이미지',
                'verbose_name_plural': '운동이미지',
            },
        ),
    ]
