# Generated by Django 2.2.8 on 2019-12-12 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20191212_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.ExerciseDescriptions', verbose_name='운동설명'),
        ),
    ]
