# Generated by Django 3.0 on 2019-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='trainer/teacher', verbose_name='트레이너 이미지'),
        ),
    ]
