# Generated by Django 2.2.8 on 2019-12-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20191211_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': '트레이너들', 'verbose_name_plural': '트레이너들'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='impact_image_url',
            field=models.ImageField(blank=True, upload_to='trainer/teacher2', verbose_name='트레이너 선택 이미지'),
        ),
    ]
