# Generated by Django 3.0 on 2019-12-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='저자명')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('weight', models.IntegerField(null=True, verbose_name='무게')),
                ('page', models.IntegerField(blank=True, verbose_name='페이지')),
                ('sale_price', models.IntegerField(blank=True, verbose_name='판매가격')),
                ('used_price', models.IntegerField(blank=True, verbose_name='중고가격')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='평점')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
            ],
        ),
    ]
