# Generated by Django 3.0 on 2019-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20191205_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='출판사 명')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='무게'),
        ),
    ]
