# Generated by Django 3.0 on 2019-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.ImageField(blank=True, upload_to='user/attachment', verbose_name='커버이미지'),
        ),
    ]
