# Generated by Django 3.0 on 2019-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.ImageField(blank=True, upload_to='book/sign', verbose_name='커버이미지'),
        ),
    ]
