# Generated by Django 3.0 on 2019-12-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191206_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(null=True, verbose_name='페이지'),
        ),
        migrations.AlterField(
            model_name='book',
            name='sale_price',
            field=models.IntegerField(null=True, verbose_name='판매가격'),
        ),
        migrations.AlterField(
            model_name='book',
            name='used_price',
            field=models.IntegerField(null=True, verbose_name='중고가격'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='무게'),
        ),
    ]
